### ISSUE TITLE
Getting errors when running

### ISSUE THREAD

**Issue by dullcibus** [Tweeticoats/stash-plugin-scrape_with#2]
First of all thanks for the plugin!
When I try to run it I get the following errors, perhaps they are caused by stash v0.6.0? I see v0.5.0 was the one that was released on last commit here.

```
DEBU[2021-04-01 02:01:17] [Plugin] Mode: scrape_all
ERRO[2021-04-01 02:01:17] [Plugin] Traceback (most recent call last):
ERRO[2021-04-01 02:01:17] [Plugin]   File "/home/usr/.stash/plugins/stash-plugin-scrape_with/scrape_with.py", line 948, in <module>
ERRO[2021-04-01 02:01:17] [Plugin]     client.update_all_scenes_with_tags()
ERRO[2021-04-01 02:01:17] [Plugin]   File "/home/usr/.stash/plugins/stash-plugin-scrape_with/scrape_with.py", line 634, in update_all_scenes_with_tags
ERRO[2021-04-01 02:01:17] [Plugin]     tags=self.listTags()
ERRO[2021-04-01 02:01:17] [Plugin]   File "/home/usr/.stash/plugins/stash-plugin-scrape_with/scrape_with.py", line 81, in listTags
ERRO[2021-04-01 02:01:17] [Plugin]     result = self.__callGraphQL(query)
ERRO[2021-04-01 02:01:17] [Plugin]   File "/home/usr/.stash/plugins/stash-plugin-scrape_with/scrape_with.py", line 70, in __callGraphQL
ERRO[2021-04-01 02:01:17] [Plugin]     query, variables))
ERRO[2021-04-01 02:01:17] [Plugin] Exception: GraphQL query failed:401 - b''. Query:                     
ERRO[2021-04-01 02:01:17] [Plugin]     query {
ERRO[2021-04-01 02:01:17] [Plugin]       allTags {
ERRO[2021-04-01 02:01:17] [Plugin]         id
ERRO[2021-04-01 02:01:17] [Plugin]         name
ERRO[2021-04-01 02:01:17] [Plugin]       }
ERRO[2021-04-01 02:01:17] [Plugin]     }. Variables: None
ERRO[2021-04-01 02:01:17] Plugin returned error: exit status 1

```

```
DEBU[2021-04-01 02:09:52] [Plugin] Mode: setup                         
ERRO[2021-04-01 02:09:52] [Plugin] Traceback (most recent call last):  
ERRO[2021-04-01 02:09:52] [Plugin]   File "/home/usr/.stash/plugins/stash-plugin-scrape_with/scrape_with.py", line 946, in <module> 
ERRO[2021-04-01 02:09:52] [Plugin]     client.setup_tags()             
ERRO[2021-04-01 02:09:52] [Plugin]   File "/home/usr.stash/plugins/stash-plugin-scrape_with/scrape_with.py", line 545, in setup_tags 
ERRO[2021-04-01 02:09:52] [Plugin]     scrapers=self.list_scrapers('FRAGMENT') 
ERRO[2021-04-01 02:09:52] [Plugin]   File "/home/usr/.stash/plugins/stash-plugin-scrape_with/scrape_with.py", line 179, in list_scrapers 
ERRO[2021-04-01 02:09:52] [Plugin]     result = self.__callGraphQL(query) 
ERRO[2021-04-01 02:09:52] [Plugin]   File "/home/usr/.stash/plugins/stash-plugin-scrape_with/scrape_with.py", line 70, in __callGraphQL 
ERRO[2021-04-01 02:09:52] [Plugin]     query, variables))              
ERRO[2021-04-01 02:09:52] [Plugin] Exception: GraphQL query failed:401 - b''. Query:  
ERRO[2021-04-01 02:09:52] [Plugin]         query listSceneScrapers {   
ERRO[2021-04-01 02:09:52] [Plugin]   listSceneScrapers {               
ERRO[2021-04-01 02:09:52] [Plugin]     id                              
ERRO[2021-04-01 02:09:52] [Plugin]     name                            
ERRO[2021-04-01 02:09:52] [Plugin]     scene{                          
ERRO[2021-04-01 02:09:52] [Plugin]       supported_scrapes             
ERRO[2021-04-01 02:09:52] [Plugin]     }                               
ERRO[2021-04-01 02:09:52] [Plugin]   }                                 
ERRO[2021-04-01 02:09:52] [Plugin] }. Variables: None                  
ERRO[2021-04-01 02:09:52] Plugin returned error: exit status 1         

```

**Comment by pibi73** [comment]
I have the same problem with 0.6 .0 .

:(

**Comment by dullcibus** [comment]
Did a little digging and found out that the issue is by having authentication enabled in stash, it seems like the graphql queries in the plugin don't expect any authentication to be present.

A possible workaround until this is fixed is to turn off the authentication temporarily, run the plugin and then re-enable the authentication.

**Comment by Jerrk** [comment]
You can add you API key to scrape_with.py under headers like
```
class scrape_with:
    headers = {
        "ApiKey":"your api key",
        "Accept-Encoding": "gzip, deflate, br",
        "Content-Type": "application/json",
        "Accept": "application/json",
        "Connection": "keep-alive",
        "DNT": "1"
    }   
```
